// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// The real ISettlementTarget implementation DecisionRelay.sol has
// called into (settlementTarget[domain].settle(...)) since it was
// written, but which never existed until now — see docs/hyperlane-
// integration.md's open question #4 and the audit findings this fixes
// (case creation used to hardcode escrowId to zero because there was
// nothing real to bind it to).
//
// Native-ETH only for this first version, matching this project's
// other MVP scope decisions (see DecisionRelay.sol/DeliveryProofReceiver.sol
// headers) — ERC20 support is a real, separate extension once this
// path is proven, not added speculatively here.
//
// Scope, stated explicitly:
//   1. A depositor (either party, or a neutral third party — this
//      contract doesn't care who funds it, only that the amount and
//      addresses match at settlement time) locks ETH against a specific
//      (caseId, escrowId) pair, naming the claimant/respondent
//      addresses up front.
//   2. Only the configured DecisionRelay address may call settle() —
//      the same real trust boundary DecisionRelay itself enforces
//      (M-of-N attestor signatures) is what authorizes a payout here;
//      this contract does not re-verify attestations itself, it trusts
//      the single caller identity, exactly as ISettlementTarget's own
//      design intends.
//   3. settle() pays out claimantAmount + respondentAmount, which MUST
//      exactly equal the amount actually deposited — this contract
//      will not pay out more than was really escrowed, and will not
//      silently accept a mismatched settlement instruction.
interface IEscrowSettlementTarget {
    function settle(bytes32 caseId, bytes32 escrowId, uint256 claimantAmount, uint256 respondentAmount, bytes32 proofHash) external;
}

contract Escrow is IEscrowSettlementTarget {
    enum Status {
        NONE,
        DEPOSITED,
        SETTLED
    }

    struct Deposit {
        Status status;
        address claimant;
        address respondent;
        uint256 amount;
        // Real fix (external audit finding): the first version of this
        // contract only emitted caseId in the Deposited event — it was
        // never stored, so settle() (keyed solely by escrowId) had no
        // on-chain way to prove a given settlement's caseId actually
        // matched the deposit's original caseId. Off-chain records
        // (CaseSettlement) enforced that binding, but the contract
        // itself couldn't. Now stored and checked in settle() below.
        bytes32 caseId;
    }

    // The only address ever allowed to call settle() — set once at
    // deploy time, immutable so it can't be silently redirected later.
    // This is deliberately the DecisionRelay contract address, not an
    // EOA: DecisionRelay is itself what enforces the real M-of-N
    // attestor threshold before ever calling settle(), so trusting this
    // one address is trusting that entire verified chain, not a single
    // private key.
    address public immutable decisionRelay;

    mapping(bytes32 => Deposit) public deposits;

    event Deposited(bytes32 indexed caseId, bytes32 indexed escrowId, address indexed depositor, address claimant, address respondent, uint256 amount);
    event Settled(bytes32 indexed caseId, bytes32 indexed escrowId, uint256 claimantAmount, uint256 respondentAmount, bytes32 proofHash);

    error AlreadyDeposited(bytes32 escrowId);
    error UnknownEscrow(bytes32 escrowId);
    error AlreadySettled(bytes32 escrowId);
    error AmountMismatch(uint256 expected, uint256 supplied);
    error CaseIdMismatch(bytes32 expected, bytes32 supplied);
    error ZeroAddress();
    error ZeroAmount();
    error NotDecisionRelay();
    error TransferFailed(address to, uint256 amount);

    constructor(address _decisionRelay) {
        if (_decisionRelay == address(0)) revert ZeroAddress();
        decisionRelay = _decisionRelay;
    }

    modifier onlyDecisionRelay() {
        if (msg.sender != decisionRelay) revert NotDecisionRelay();
        _;
    }

    /// Locks msg.value against (caseId, escrowId), naming the two
    /// parties this specific escrow can ever pay out to. escrowId is
    /// caller-chosen (expected to be a fresh id per case, generated by
    /// the depositor/backend) — this contract's own guard is simply
    /// "an escrowId can only ever be deposited into once," which is
    /// sufficient to prevent a deposit being silently overwritten or
    /// mixed with an unrelated case, regardless of how escrowId was
    /// chosen upstream.
    function deposit(bytes32 caseId, bytes32 escrowId, address claimant, address respondent) external payable {
        if (deposits[escrowId].status != Status.NONE) revert AlreadyDeposited(escrowId);
        if (claimant == address(0) || respondent == address(0)) revert ZeroAddress();
        if (msg.value == 0) revert ZeroAmount();

        deposits[escrowId] = Deposit({ status: Status.DEPOSITED, claimant: claimant, respondent: respondent, amount: msg.value, caseId: caseId });

        emit Deposited(caseId, escrowId, msg.sender, claimant, respondent, msg.value);
    }

    /// Called only by DecisionRelay after it has independently verified
    /// M-of-N attestor signatures over this exact settlement — see this
    /// contract's own header comment. Reverts (rather than silently
    /// no-op-ing) on any mismatch between what was actually deposited
    /// and what's being asked to pay out, so a bug or attempted forgery
    /// upstream surfaces immediately instead of moving the wrong amount.
    function settle(bytes32 caseId, bytes32 escrowId, uint256 claimantAmount, uint256 respondentAmount, bytes32 proofHash) external onlyDecisionRelay {
        Deposit storage d = deposits[escrowId];
        if (d.status == Status.NONE) revert UnknownEscrow(escrowId);
        if (d.status == Status.SETTLED) revert AlreadySettled(escrowId);
        if (caseId != d.caseId) revert CaseIdMismatch(d.caseId, caseId);
        uint256 total = claimantAmount + respondentAmount;
        if (total != d.amount) revert AmountMismatch(d.amount, total);

        // Effects before interactions: mark settled, and capture the
        // payout addresses/amounts into locals, BEFORE either external
        // transfer — a reentrant call back into settle() or deposit()
        // for this same escrowId sees Status.SETTLED and reverts
        // immediately, regardless of what either transfer below does.
        d.status = Status.SETTLED;
        address claimant = d.claimant;
        address respondent = d.respondent;

        emit Settled(caseId, escrowId, claimantAmount, respondentAmount, proofHash);

        if (claimantAmount > 0) {
            (bool ok, ) = claimant.call{ value: claimantAmount }("");
            if (!ok) revert TransferFailed(claimant, claimantAmount);
        }
        if (respondentAmount > 0) {
            (bool ok, ) = respondent.call{ value: respondentAmount }("");
            if (!ok) revert TransferFailed(respondent, respondentAmount);
        }
    }
}
